site_name: ControlPlane Enterprise for Flux CD
site_description: |
  ControlPlane offers a hardened, enterprise-grade distribution and
  support services for the CNCF-graduated Flux project.
site_author: ControlPLane
site_url: https://fluxcd.control-plane.io
repo_name: distribution
repo_url: https://github.com/controlplaneio-fluxcd/distribution
edit_uri: ""
copyright: Copyright © 2025 ControlPlane Ltd.

home:
  image: images/flux-ee-white.png
  tagline: Assured Flux CD
  description: |
    ControlPlane Enterprise enhances the security and stability of
    Kubernetes GitOps delivery through comprehensive security assurance
    and compliance with required regulatory standards for Flux CD.
    The enterprise distribution extends Flux with self-service features
    and AI-assisted GitOps capabilities.
  features: true

theme:
  name: material
  logo: images/cp-logo.png
  favicon: images/cp-logo.png
  language: en
  custom_dir: docs/theme/
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - navigation.sections
    - navigation.top
    - navigation.tabs

extra:
  social:
    - icon: fontawesome/brands/square-x-twitter
      link: https://x.com/controlplaneio
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/controlplane/mycompany/

docs_dir: docs

plugins:
  - search
  - social

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - meta
  - codehilite
  - footnotes
  - pymdownx.tilde
  - pymdownx.progressbar
  - pymdownx.tasklist
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Flux Distribution:
    - Introduction: distribution/index.md
    - Installation: distribution/install.md
    - Security: distribution/security.md
    - Guides:
        - Flux Architecture Overview: guides/flux-architecture.md
        - D1 Reference Architecture: guides/d1-architecture-reference.md
        - D2 Reference Architecture: guides/d2-architecture-reference.md
        - Flux Multitenant Policies: guides/flux-policies.md
        - Generic Helm Chart Pattern: guides/flux-generic-helm-chart.md
        - Flux CLI Quick Reference: guides/flux-cli-quick-reference.md
    - Marketplaces:
        - AWS Marketplace: marketplace/aws.md
    - Versions:
        - Release v2.7: releases/release-v2.7.md
        - Release v2.6: releases/release-v2.6.md
        - Release v2.5: releases/release-v2.5.md
        - Release v2.4: releases/release-v2.4.md
        - Release v2.3: releases/release-v2.3.md
        - Release v2.2: releases/release-v2.2.md
  - Flux Operator:
      - Introduction: operator/index.md
      - Installation: operator/install.md
      - Instance Configuration:
          - Flux Controllers: operator/flux-config.md
          - Flux Cluster Sync: operator/flux-sync.md
          - Flux Customization: operator/flux-kustomize.md
          - Flux Sharding: operator/flux-sharding.md
          - Flux Monitoring: operator/monitoring.md
          - Bootstrap Migration: operator/flux-bootstrap-migration.md
      - ResourceSet Guides:
          - Introduction: operator/resourcesets/introduction.md
          - Application Definitions: operator/resourcesets/app-definition.md
          - Time-based App Delivery: operator/resourcesets/time-based-delivery.md
          - Image Update Automation: operator/resourcesets/image-automation.md
          - Self-Service Environments:
            -  Ephemeral Environments for GitHub Pull Requests: operator/resourcesets/github-pull-requests.md
            -  Ephemeral Environments for GitLab Merge Requests: operator/resourcesets/gitlab-merge-requests.md
      - API Reference:
          - FluxInstance: operator/fluxinstance.md
          - FluxReport: operator/fluxreport.md
          - ResourceSet: operator/resourceset.md
          - ResourceSetInputProvider: operator/resourcesetinputprovider.md
      - CLI Reference: operator/cli.md
  - Flux MCP Server:
      - Introduction: mcp/index.md
      - Installation: mcp/install.md
      - Configuration: mcp/config.md
      - Guides:
          - Prompt Engineering: mcp/prompt-engineering.md
          - AI Instructions: mcp/instructions.md
      - API Reference:
          - Config API: mcp/config-api.md
          - MCP Tools: mcp/tools.md
          - MCP Prompts: mcp/prompts.md
  - Pricing: pricing/index.md
  - Contact: https://control-plane.io/contact/?inquiry=fluxcd
