apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: dex
spec:
  url: oci://ghcr.io/controlplaneio-fluxcd/charts/dex
  ref:
    tag: 0.24.0
    digest: sha256:cd97cd96930b9227b1bad69717ff25247a73cd5c10b19a147a371e077601eed7
