name: Update Flux manifests
description: A GitHub Action for updating Flux manifests in bootstrap repositories
author: Stefan Prodan
branding:
  color: blue
  icon: command
inputs:
  registry:
    description: "Distribution Container Registry"
    default: "ghcr.io/controlplaneio-fluxcd"
    required: true
  variant:
    description: "Base image variant e.g. alpine or distroless"
    default: "alpine"
    required: true
  components:
    description: "Flux components comma separated list e.g. source-controller,kustomize-controller"
    default: "source-controller,kustomize-controller,helm-controller,notification-controller,image-reflector-controller,image-automation-controller"
    required: true
  path:
    description: "Path to the flux-system dir e.g. clusters/production/flux-system/"
    required: true
  image-pull-secret:
    description: "Name of the Kubernetes image pull secret for accessing the distribution registry"
    required: false
  version:
    description: "Distribution version e.g. v2.5.0 (defaults to latest stable release)"
    required: false
  bindir:
    description: "Alternative location for the Flux binary, defaults to path relative to $RUNNER_TOOL_CACHE."
    required: false
  distribution-url:
    description: "Distribution images info URL"
    default: "https://raw.githubusercontent.com/controlplaneio-fluxcd/distribution/main/images"
    required: false
outputs:
  version:
    description: "Flux version"
    value: ${{ steps.cli.outputs.version }}
runs:
  using: composite
  steps:
    - name: "Download the Flux CLI binary to the runner's cache dir"
      id: cli
      shell: bash
      run: |
        VERSION=${{ inputs.version }}

        if [[ -z "$VERSION" ]] || [[ "$VERSION" = "latest" ]]; then
          VERSION=$(curl -fsSL ${{ inputs.distribution-url }}/VERSION | head -n1)
        fi
        if [[ -z "$VERSION" ]]; then
          echo "Unable to determine the latest distribution version"
          exit 1
        fi
        if [[ $VERSION = v* ]]; then
          VERSION="${VERSION:1}"
        fi

        OS=$(echo "${RUNNER_OS}" | tr '[:upper:]' '[:lower:]')
        if [[ "$OS" == "macos" ]]; then
          OS="darwin"
        fi

        ARCH=$(echo "${RUNNER_ARCH}" | tr '[:upper:]' '[:lower:]')
        if [[ "$ARCH" == "x64" ]]; then
          ARCH="amd64"
        elif [[ "$ARCH" == "x86" ]]; then
          ARCH="386"
        fi

        FLUX_EXEC_FILE="flux"
        if [[ "$OS" == "windows" ]]; then
            FLUX_EXEC_FILE="${FLUX_EXEC_FILE}.exe"
        fi

        FLUX_TOOL_DIR=${{ inputs.bindir }}
        if [[ -z "$FLUX_TOOL_DIR" ]]; then
          FLUX_TOOL_DIR="${RUNNER_TOOL_CACHE}/flux2/${VERSION}/${OS}/${ARCH}"
        fi
        if [[ ! -x "$FLUX_TOOL_DIR/FLUX_EXEC_FILE" ]]; then
          DL_DIR="$(mktemp -dt flux2-XXXXXX)"
          trap 'rm -rf $DL_DIR' EXIT

          echo "Downloading flux ${VERSION} for ${OS}/${ARCH}"
          FLUX_TARGET_FILE="flux_${VERSION}_${OS}_${ARCH}.tar.gz"
          if [[ "$OS" == "windows" ]]; then
            FLUX_TARGET_FILE="flux_${VERSION}_${OS}_${ARCH}.zip"
          fi

          FLUX_CHECKSUMS_FILE="flux_${VERSION}_checksums.txt"

          FLUX_DOWNLOAD_URL="https://github.com/fluxcd/flux2/releases/download/v${VERSION}/"

          curl -fsSL -o "$DL_DIR/$FLUX_TARGET_FILE" "$FLUX_DOWNLOAD_URL/$FLUX_TARGET_FILE"
          curl -fsSL -o "$DL_DIR/$FLUX_CHECKSUMS_FILE" "$FLUX_DOWNLOAD_URL/$FLUX_CHECKSUMS_FILE"

          echo "Verifying checksum"
          sum=""
          if command -v openssl > /dev/null; then
            sum=$(openssl sha256 "$DL_DIR/$FLUX_TARGET_FILE" | awk '{print $2}')
          elif command -v sha256sum > /dev/null; then
            sum=$(sha256sum "$DL_DIR/$FLUX_TARGET_FILE" | awk '{print $1}')
          fi

          if [[ -z "$sum" ]]; then
            echo "Neither openssl nor sha256sum found. Cannot calculate checksum."
            exit 1
          fi

          expected_sum=$(grep " $FLUX_TARGET_FILE\$" "$DL_DIR/$FLUX_CHECKSUMS_FILE" | awk '{print $1}')
          if [ "$sum" != "$expected_sum" ]; then
            echo "SHA sum of ${FLUX_TARGET_FILE} does not match. Aborting."
            exit 1
          fi

          echo "Installing flux to ${FLUX_TOOL_DIR}"
          mkdir -p "$FLUX_TOOL_DIR"
        
          if [[ "$OS" == "windows" ]]; then
            unzip "$DL_DIR/$FLUX_TARGET_FILE" "$FLUX_EXEC_FILE" -d "$FLUX_TOOL_DIR"
          else
            tar xzf "$DL_DIR/$FLUX_TARGET_FILE" -C "$FLUX_TOOL_DIR" $FLUX_EXEC_FILE
          fi

          chmod +x "$FLUX_TOOL_DIR/$FLUX_EXEC_FILE"
        fi

        echo "Adding flux to path"
        echo "$FLUX_TOOL_DIR" >> "$GITHUB_PATH"
        echo "version=v${VERSION}" >> "$GITHUB_OUTPUT"
    - name: "Update components manifests"
      shell: bash
      run: |
        registry=${{ inputs.registry }}
        if [[ "${{ inputs.registry }}" == "ghcr.io/controlplaneio-fluxcd" ]]; then
          registry=${{ inputs.registry }}/${{ inputs.variant }}
        fi
        cd ${{ inputs.path }}
        flux install \
        --components="${{ inputs.components }}" \
        --registry=${registry} \
        --image-pull-secret=${{ inputs.image-pull-secret }} \
        --export > gotk-components.yaml
    - name: "Update images digests"
      shell: bash
      run: |
        if [[ "${{ inputs.registry }}" != "ghcr.io/controlplaneio-fluxcd" ]]; then
          exit 0
        fi
        cd ${{ inputs.path }}
        version=$(flux -v | awk '{ print $3 }')
        images_url="${{ inputs.distribution-url }}/v${version}/enterprise-${{ inputs.variant }}.yaml"
        curl -fsSL -o enterprise-images.yaml ${images_url}
        yq '. *= load("enterprise-images.yaml")' kustomization.yaml > kustomization.yaml.tmp
        mv kustomization.yaml.tmp kustomization.yaml
        rm enterprise-images.yaml
