name: Migrate Flux manifests
description: A GitHub Action for migrating Flux manifests to their latest API version
author: Stefan Prodan
branding:
  color: blue
  icon: command
inputs:
  version:
    description: "Flux major.minor version e.g. 2.7 (defaults to latest stable release)"
    required: false
  path:
    description: "Path to the directory containing the manifests to migrate"
    default: "."
    required: false
  extensions:
    description: "Comma separated list of file extensions to consider"
    default: ".yaml,.yml"
    required: false
runs:
  using: composite
  steps:
    - name: Check if the Flux CLI is installed
      shell: bash
      run: |
        if ! flux version --client > /dev/null 2>&1; then
          echo "The Flux CLI is not installed. Please install it first using this GitHub Action:"
          echo ""
          echo "  https://github.com/controlplaneio-fluxcd/distribution/tree/main/actions/setup"
          echo ""
          exit 1
        fi
    - name: "Migrate manifests"
      shell: bash
      env:
        MIGRATE_PATH: ${{ inputs.path }}
        MIGRATE_EXTENSIONS: ${{ inputs.extensions }}
        MIGRATE_VERSION: ${{ inputs.version }}
      run: |
        PATH_ARG="$MIGRATE_PATH"
        if [[ -z "$PATH_ARG" ]]; then
          PATH_ARG="."
        fi
        ARGS=(--yes --path "$PATH_ARG")
        if [[ -n "$MIGRATE_EXTENSIONS" ]]; then
          ARGS+=(--extensions "$MIGRATE_EXTENSIONS")
        fi
        if [[ -n "$MIGRATE_VERSION" ]]; then
          ARGS+=(--version "$MIGRATE_VERSION")
        fi
        flux migrate "${ARGS[@]}"
