name: License scan

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Flux version'
        required: false
  push:
    branches:
      - 'main'
      - 'license-*'

jobs:
  trivy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Latest release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(gh release view --json tagName -q '.tagName')
          if [ "${{ github.event.inputs.version }}" != "" ]; then
            VERSION="${{ github.event.inputs.version }}"
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
      - name: Checkout Flux
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: fluxcd/flux2
          ref: ${{ steps.release.outputs.version }}
      - name: Setup Go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version-file: 'go.mod'
      - name: Download Flux dependencies
        run: |         
          make tidy
      - name: Setup Trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy
      - name: License report
        run: |
          trivy fs -q --format table --scanners  license --severity  UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL ./go.mod
      - name: License check
        run: |
          trivy fs -q --format table --scanners  license --severity  UNKNOWN,HIGH,CRITICAL ./go.mod --exit-code 1
