name: Upstream vulnerability scan

on:
  workflow_dispatch:
  schedule:
    - cron: '00 3 * * 1-5'

permissions:
  contents: read

jobs:
  scan:
    permissions:
      contents: read
    uses: ./.github/workflows/x-scan-controllers.yaml
    with:
      check-scan-error: false
      registry: ghcr.io/fluxcd
    secrets:
      pull-token: ${{ secrets.GHCR_READONLY }}
