name: Vulnerability scan

on:
  workflow_dispatch:
  schedule:
    - cron: '00 4 * * 1-5'

permissions:
  contents: read

jobs:
  scan:
    strategy:
      fail-fast: false
      matrix:
        variant:
          - alpine
          - distroless
    permissions:
      contents: read
    uses: ./.github/workflows/scan-controllers.yaml
    with:
      check-scan-error: true
      registry: ghcr.io/controlplaneio-fluxcd/${{ matrix.variant }}
    secrets:
      pull-token: ${{ secrets.GHCR_READONLY }}
