name: Update images

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Flux version'
        required: false

permissions:
  contents: read

env:
  ENTERPRISE_REGISTRY: ghcr.io/controlplaneio-fluxcd
  ENTERPRISE_VARIANTS: alpine;distroless;distroless-fips

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_READONLY }}
      - name: Latest release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(gh release view --json tagName -q '.tagName')
          
          if [ "${{ github.event.inputs.version }}" != "" ]; then
            VERSION="${{ github.event.inputs.version }}"
          fi
          
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
      - name: Setup Flux
        uses: fluxcd/flux2/action@1fd61a06264d71cf445ed55c4f14d401d26a1c64 #v2.8.8
        with:
          version: ${{ steps.release.outputs.version }}
      - name: Enterprise images
        shell: bash
        run: |
          for variant in ${ENTERPRISE_VARIANTS//;/$'\n'}
          do
            DISTRIBUTION="enterprise" \
            REGISTRY="${ENTERPRISE_REGISTRY}" \
            VARIANT="${variant}" \
            VERSION="${{ steps.release.outputs.version }}" \
            .github/workflows/update-images.sh
          done
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: |
            Update images for Flux ${{ steps.release.outputs.version }}
          committer: GitHub <noreply@github.com>
          signoff: true
          branch: update-images-${{ steps.release.outputs.version }}
          title: Update images for Flux ${{ steps.release.outputs.version }}
          body: |
            Update images with digests for Flux ${{ steps.release.outputs.version }}
          labels: |
            area/images
